# Generated by Django 4.2.6 on 2023-12-07 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('product_type', models.CharField(choices=[('MOBILE', 'Mobile'), ('TV', 'TV'), ('CAMERA', 'Camera'), ('LAPTOP', 'Laptop'), ('TABLET', 'Tablet'), ('SPEAKER', 'Speaker')], max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('stock', models.IntegerField()),
                ('image', models.ImageField(upload_to='product_images/')),
            ],
        ),
    ]
