# Generated by Django 4.2.6 on 2023-12-08 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customproduct',
            name='image',
            field=models.ImageField(blank=True, upload_to='product_images/'),
        ),
    ]
