# Generated by Django 4.2.7 on 2023-11-20 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customemployee',
            name='password',
            field=models.CharField(default='1', max_length=128),
        ),
    ]
