# Generated by Django 4.2.6 on 2023-11-25 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_customemployee_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customemployee',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='customemployee',
            name='user_permissions',
        ),
    ]
