# Generated by Django 4.2.6 on 2023-11-26 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_customemployee_groups_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomEmployee',
        ),
        migrations.AddField(
            model_name='customuser',
            name='access_level',
            field=models.CharField(default='admin', max_length=50),
        ),
        migrations.AddField(
            model_name='customuser',
            name='office',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(default='1', max_length=128),
        ),
    ]
