# Generated by Django 4.2.6 on 2023-11-26 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_delete_customemployee_customuser_access_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='office',
            field=models.CharField(default='Cliente', max_length=100),
        ),
    ]
