# Generated by Django 4.2.6 on 2023-11-27 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_customuser_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='updated_at',
        ),
    ]
