# Generated by Django 4.2.6 on 2023-11-27 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_customuser_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='created_at',
            field=models.DateTimeField(default='2023-11-26 22:33:25.572915'),
            preserve_default=False,
        ),
    ]
