# Generated by Django 4.2.6 on 2023-11-27 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_remove_customuser_updated_at'),
        ('user', '0011_alter_customuser_created_at'),
    ]

    operations = [
    ]
